#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "emit.h"

/*
 * Stage-2 C builder: shaken dir -> C NativeFunctions + Makefile/CMake + exe.
 *   yggdrasil-build <shaken-dir> <out-dir>
 *
 * Writes <out-dir>/app.c, Makefile, CMakeLists.txt, then `make` builds
 * <out-dir>/app linked against bin/libshenc.a (shen_context / Boehm).
 */

static char* read_file (const char* path)
{
  FILE* file = fopen(path, "rb");
  long size;
  char* text;

  if (file == NULL)
    return NULL;

  fseek(file, 0, SEEK_END);
  size = ftell(file);
  fseek(file, 0, SEEK_SET);
  text = malloc((size_t)size + 1);

  if (text == NULL) {
    fclose(file);
    return NULL;
  }

  if (size > 0 && fread(text, 1, (size_t)size, file) != (size_t)size) {
    fclose(file);
    return NULL;
  }

  text[size] = '\0';
  fclose(file);

  return text;
}

static void join_path (char* out, size_t cap, const char* a, const char* b)
{
  snprintf(out, cap, "%s/%s", a, b);
}

static void strip_trailing_slashes (char* path)
{
  size_t n = strlen(path);

  while (n > 1 && path[n - 1] == '/') {
    path[n - 1] = '\0';
    n--;
  }
}

static int mkdir_p (const char* path)
{
  char buf[4096];
  size_t n;
  size_t i;
  struct stat status;

  n = strlen(path);

  if (n == 0 || n >= sizeof(buf))
    return -1;

  memcpy(buf, path, n + 1);

  for (i = 1; i < n; ++i) {
    if (buf[i] == '/') {
      buf[i] = '\0';

      if (buf[0] != '\0' && mkdir(buf, 0755) != 0 && errno != EEXIST)
        return -1;

      buf[i] = '/';
    }
  }

  if (stat(path, &status) == 0) {
    if (S_ISDIR(status.st_mode))
      return 0;

    if (unlink(path) != 0)
      return -1;
  }

  if (mkdir(path, 0755) != 0 && errno != EEXIST)
    return -1;

  return 0;
}

static int write_text (const char* path, const char* text)
{
  FILE* file = fopen(path, "w");

  if (file == NULL)
    return -1;

  if (fputs(text, file) == EOF) {
    fclose(file);
    return -1;
  }

  fclose(file);
  return 0;
}

static void shell_quote (char* out, size_t cap, const char* s)
{
  size_t n = 0;

  if (cap < 3) {
    if (cap > 0)
      out[0] = '\0';
    return;
  }

  out[n++] = '\'';

  for (; *s != '\0' && n + 6 < cap; ++s) {
    if (*s == '\'') {
      out[n++] = '\'';
      out[n++] = '\\';
      out[n++] = '\'';
      out[n++] = '\'';
    } else {
      out[n++] = *s;
    }
  }

  out[n++] = '\'';
  out[n] = '\0';
}

static void makefile_escape (char* out, size_t cap, const char* s)
{
  size_t n = 0;

  for (; *s != '\0' && n + 3 < cap; ++s) {
    if (*s == '$')
      out[n++] = '$';
    out[n++] = *s;
  }

  out[n] = '\0';
}

static void cmake_escape (char* out, size_t cap, const char* s)
{
  size_t n = 0;

  for (; *s != '\0' && n + 3 < cap; ++s) {
    if (*s == '\\' || *s == '"')
      out[n++] = '\\';
    out[n++] = *s;
  }

  out[n] = '\0';
}

static int write_app_makefile (const char* path, const char* home, const char* cc)
{
  char home_mk[8192];
  char cc_mk[1024];
  char text[16384];

  makefile_escape(home_mk, sizeof(home_mk), home);
  makefile_escape(cc_mk, sizeof(cc_mk), cc);
  snprintf(text, sizeof(text),
           "# Generated by shen-c yggdrasil-build (option 5 rung 1).\n"
           "# Allocations stay on shen_context / Boehm. Not eval_kl_object wrap.\n"
           "SHEN_C_HOME ?= %s\n"
           "CC ?= %s\n"
           "PKG_CONFIG ?= pkg-config\n"
           "CFLAGS ?= -O2\n"
           "CFLAGS += -std=c17 -fno-optimize-sibling-calls -fsigned-char\n"
           "CFLAGS += $(shell $(PKG_CONFIG) --cflags bdw-gc)\n"
           "CFLAGS += -iquote $(SHEN_C_HOME)/src/c\n"
           "LIBS = $(SHEN_C_HOME)/bin/libshenc.a "
           "$(shell $(PKG_CONFIG) --libs bdw-gc)\n"
           "\n"
           "app: app.c\n"
           "\t$(CC) $(CFLAGS) app.c $(LIBS) -o app\n"
           "\n"
           ".PHONY: cmake-ninja\n"
           "cmake-ninja:\n"
           "\tcmake -G Ninja -S . -B build -D SHEN_C_HOME=$(SHEN_C_HOME)\n"
           "\tcmake --build build\n",
           home_mk, cc_mk);

  return write_text(path, text);
}

static int write_app_cmakelists (const char* path, const char* home)
{
  char home_cm[8192];
  char text[16384];

  cmake_escape(home_cm, sizeof(home_cm), home);
  snprintf(text, sizeof(text),
           "cmake_minimum_required(VERSION 3.16)\n"
           "project(yggdrasil_app C)\n"
           "set(CMAKE_C_STANDARD 17)\n"
           "set(CMAKE_C_STANDARD_REQUIRED ON)\n"
           "set(CMAKE_C_EXTENSIONS OFF)\n"
           "set(SHEN_C_HOME \"%s\" CACHE PATH \"shen-c checkout\")\n"
           "find_package(PkgConfig REQUIRED)\n"
           "pkg_check_modules(BDWGC REQUIRED IMPORTED_TARGET bdw-gc)\n"
           "add_executable(app app.c)\n"
           "target_compile_options(app PRIVATE\n"
           "  -fno-optimize-sibling-calls -fsigned-char\n"
           "  \"-iquote${SHEN_C_HOME}/src/c\")\n"
           "target_link_libraries(app PRIVATE\n"
           "  \"${SHEN_C_HOME}/bin/libshenc.a\" PkgConfig::BDWGC)\n"
           "set_target_properties(app PROPERTIES\n"
           "  RUNTIME_OUTPUT_DIRECTORY \"${CMAKE_CURRENT_SOURCE_DIR}\"\n"
           "  RUNTIME_OUTPUT_DIRECTORY_DEBUG \"${CMAKE_CURRENT_SOURCE_DIR}\"\n"
           "  RUNTIME_OUTPUT_DIRECTORY_RELEASE \"${CMAKE_CURRENT_SOURCE_DIR}\")\n",
           home_cm);

  return write_text(path, text);
}

int main (int argc, char** argv)
{
  const char* shaken;
  char out_dir[4096];
  const char* home;
  const char* cc;
  char home_abs[4096];
  char manifest_path[4096];
  char kernel_path[4096];
  char c_path[4096];
  char mk_path[4096];
  char cmake_path[4096];
  char exe_path[4096];
  char cmd[16384];
  char qdir[8192];
  char qcc[1024];
  char* manifest;
  char kernel_name[256] = "kernel.kl";
  char init_name[256] = "";
  char users[32][256];
  int nusers = 0;
  char* line;
  KLObject** kernel_forms = NULL;
  long nkernel = 0;
  KLObject* user_store[4096];
  long nuser = 0;
  FILE* out;
  ShenEmitReport report = {0};
  int i;

  if (argc != 3) {
    fprintf(stderr, "usage: yggdrasil-build <shaken-dir> <out-dir>\n");
    return 2;
  }

  shaken = argv[1];
  snprintf(out_dir, sizeof(out_dir), "%s", argv[2]);
  strip_trailing_slashes(out_dir);
  home = getenv("SHEN_C_HOME");

  if (home == NULL || home[0] == '\0')
    home = ".";

  if (realpath(home, home_abs) != NULL)
    home = home_abs;

  join_path(manifest_path, sizeof(manifest_path), shaken,
            "yggdrasil.manifest.txt");
  manifest = read_file(manifest_path);

  if (manifest == NULL) {
    fprintf(stderr, "yggdrasil-build: no %s\n", manifest_path);
    return 1;
  }

  for (line = strtok(manifest, "\n"); line != NULL; line = strtok(NULL, "\n")) {
    char* eq;

    if (line[0] == '#' || line[0] == '\0')
      continue;

    eq = strchr(line, '=');

    if (eq == NULL)
      continue;

    *eq = '\0';

    if (strcmp(line, "kernel") == 0)
      snprintf(kernel_name, sizeof(kernel_name), "%s", eq + 1);
    else if (strcmp(line, "init") == 0)
      snprintf(init_name, sizeof(init_name), "%s", eq + 1);
    else if (strcmp(line, "user") == 0 && nusers < 32) {
      snprintf(users[nusers], sizeof(users[nusers]), "%s", eq + 1);
      nusers++;
    }
  }

  shen_boot(&shen_root_context, home);
  join_path(kernel_path, sizeof(kernel_path), shaken, kernel_name);

  if (shen_read_kl_path(kernel_path, &kernel_forms, &nkernel) != 0) {
    fprintf(stderr, "yggdrasil-build: cannot read %s\n", kernel_path);
    return 1;
  }

  for (i = 0; i < nusers; ++i) {
    char user_path[4096];
    KLObject** forms = NULL;
    long n = 0;
    long j;

    join_path(user_path, sizeof(user_path), shaken, users[i]);

    if (shen_read_kl_path(user_path, &forms, &n) != 0) {
      fprintf(stderr, "yggdrasil-build: cannot read %s\n", user_path);
      return 1;
    }

    for (j = 0; j < n; ++j) {
      if (nuser >= 4096) {
        fprintf(stderr, "yggdrasil-build: too many user forms\n");
        return 1;
      }

      user_store[nuser++] = forms[j];
    }
  }

  if (mkdir_p(out_dir) != 0) {
    fprintf(stderr, "yggdrasil-build: cannot mkdir %s\n", out_dir);
    return 1;
  }

  join_path(c_path, sizeof(c_path), out_dir, "app.c");
  join_path(mk_path, sizeof(mk_path), out_dir, "Makefile");
  join_path(cmake_path, sizeof(cmake_path), out_dir, "CMakeLists.txt");
  join_path(exe_path, sizeof(exe_path), out_dir, "app");

  out = fopen(c_path, "w");

  if (out == NULL) {
    fprintf(stderr, "yggdrasil-build: cannot write %s\n", c_path);
    return 1;
  }

  if (shen_emit_program(out, kernel_forms, nkernel, user_store, nuser,
                        init_name[0] ? init_name : NULL, shaken,
                        &report) != 0) {
    fprintf(stderr, "yggdrasil-build: emit failed\n");
    return 1;
  }

  fclose(out);

  {
    char lib[4096];

    snprintf(lib, sizeof(lib), "%s/bin/libshenc.a", home);

    if (access(lib, R_OK) != 0) {
      fprintf(stderr, "yggdrasil-build: missing %s (run make in shen-c)\n", lib);
      return 1;
    }
  }

  cc = getenv("CC");

  if (cc == NULL || cc[0] == '\0')
    cc = "clang";

  if (write_app_makefile(mk_path, home, cc) != 0) {
    fprintf(stderr, "yggdrasil-build: cannot write %s\n", mk_path);
    return 1;
  }

  if (write_app_cmakelists(cmake_path, home) != 0) {
    fprintf(stderr, "yggdrasil-build: cannot write %s\n", cmake_path);
    return 1;
  }

  shell_quote(qdir, sizeof(qdir), out_dir);
  shell_quote(qcc, sizeof(qcc), cc);
  snprintf(cmd, sizeof(cmd), "make -C %s CC=%s app", qdir, qcc);

  if (system(cmd) != 0) {
    fprintf(stderr, "yggdrasil-build: make failed:\n%s\n", cmd);
    return 1;
  }

  fprintf(stderr,
          "yggdrasil/c: wrote %s (app.c Makefile CMakeLists.txt; "
          "defuns=%ld toplevels=%ld lambdas=%ld)\n",
          exe_path, report.defuns, report.toplevels, report.lambdas);

  return 0;
}
